# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.4.0

      - name: Build
        run: make build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: boot.bin
